defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

hydra:
  job:
    chdir: false
  output_subdir: null
  run:
    dir: .

patch_selection:
  _target_: model.Selection.DDPS.maskclip_patch_selection
  _partial_: true
  query_file: ${invoke.query_file}
  clip_model_name: "openai/clip-vit-large-patch14"
  clip_dtype: "bf16"
  clip_do_center_crop: false
  keep_ratio: 0.1
  batch_size: 10


vlm:
  _target_: model.vlm.BaseVLM
  model_id: "llava-hf/llava-1.5-7b-hf"
  backend: "llava"
  dtype: "bf16"
  quantization:
    enabled: true
    mode: "4bit"
    skip_vision_encoder: true
    skip_modules: []
    kwargs:
      bnb_4bit_compute_dtype: "bf16"
      bnb_4bit_quant_type: "nf4"
      bnb_4bit_use_double_quant: true
      llm_int8_threshold: 6.0
      llm_int8_enable_fp32_cpu_offload: false
  patch_selector: ${patch_selection}
  image_max_side: null
  processor_kwargs: {}
  model_kwargs: 
    device_map: "cuda:0" # set specific cuda device here or "auto"
  local_model_dir: "./model/repo"
  inference_batch_size: 48 # set inference batch size here (config/eval.yaml vqav2.eval_batch_size has higher priority than this option)
  generation_kwargs:
    do_sample: false
    max_new_tokens: 10

invoke:
  task: "vqa"
  image_path: "./data/image.png"
  prompt_file: "model/prompt.txt"
  query_file: "model/query.txt"
  print_config: false
  quiet_model_loading: true
